### ISSUE TITLE
undefined method `keys' for nil:NilClass for all existing fresh_when calls

### ISSUE THREAD

**Issue by giuseb** [cloudspace/ettu#2]
Just stumbled upon the problem that led to the development of this gem.

Added `gem 'ettu'` to my `rails 3.2.13` app's `Gemfile`, added `config.action_view.cache_template_loading = false` to development.rb, bundled, restarted the server.

Now, all controller actions that invoke something like:

```
fresh_when @exam
```

raise the error. Here's a snippet of a sample stack trace, I can provide more details, if necessary.

![screen shot 2013-10-23 at 10 59 04](https://f.cloud.github.com/assets/10086/1388650/1e01654c-3bc3-11e3-8746-6dc9fc8cc24f.png)

**Comment by jridgewell** [comment]
What version/implementation of ruby are you using?

**Comment by giuseb** [comment]
mri 1.9.3

**Comment by jridgewell** [comment]
I think I've tracked down the error in https://github.com/cloudspace/ettu/commit/5ed9c829a18b5aa9ef244f20808a9976df9f01d9.

I've tested locally, but before I push a new version could I get you to test it as well? Modifying your Gemfile with

``` ruby
gem 'ettu', :github => 'cloudspace/ettu', :branch => 'v3'
```

and `bundle install`ing will run the v3 "master" branch without installing it to your system.

**Comment by giuseb** [comment]
It does work, thanks!

Quick question: the functionality provided by this gem appears to me so fundamental that I cannot figure out why it's not part of rails itself. Am I missing something? How do people expire http caches across deployments otherwise??

Thanks again...

**Comment by jridgewell** [comment]
Sweet. Closing this with version 3.1.1 that's just been pushed.

I think rails want you to change ENV["RAILS_CACHE_ID"] to bust etags by default, but I never liked that option. (Usually it'd be built into your deploy steps, but a new deploy doesn't necessarily mean my assets have changed.)
