### ISSUE TITLE
seems to collide with rails 4.1.0

### ISSUE THREAD

**Issue by Rockfordal** [cloudspace/ettu#5]
i got some error about parameters 3 for 1 for every stale? and fresh_when i had

**Comment by jridgewell** [comment]
Seems Rails decided to change `ActionView::Digestor.digest`'s arguments to a hash between [v4.1.0.rc1](https://github.com/rails/rails/blob/v4.1.0.rc1/actionview/lib/action_view/digestor.rb) and [v4.1.0.rc2](https://github.com/rails/rails/blob/v4.1.0.rc2/actionview/lib/action_view/digestor.rb). Unfortunately, we never tested rc2, just [rc1](https://github.com/cloudspace/ettu/blob/master/gemfiles/4.1.gemfile).

Worse, this change was [supposed to be a deprecation](https://github.com/rails/rails/commit/1858cc60701dcfb801b9634a1da0177eaeba3807), and not an outright change.

The positive side is we'll get to [remove some weird params](https://github.com/cloudspace/ettu/blob/v4.1.8/lib/ettu.rb#L71) from our `fresh_when` call.

I've just pushed [v4.1.8](https://github.com/cloudspace/ettu/tree/v4.1.8), which only changes the Rails dependency to `~> 4.0.0`. This'll be the version Rails 4.0.\* devs get when bundling. I've also pushed [v4.2.0](https://github.com/cloudspace/ettu/tree/v4.2.0), which fixes support with Rails 4.1.
